allow newer versions of yum-epel cookbook
zuazo/opendkim-cookbook pull request #2
Opened 2018-03-07 05:20 UTC by mburns

### Description

Allow newer versions (`0.5.x - 3.x.y`, inclusive) of the `yum-epel` cookbook, to support nodes using newer versions of Chef that don't support the [most recent version supported by the cookbook](https://github.com/chef-cookbooks/yum-epel/releases/tag/v0.7.1).

[yum-epel](https://github.com/chef-cookbooks/yum-epel) is on `v3.1.0` and this cookbook shouldn't have any breaking changes by allowing newer versions as dependencies, given our simple use case.

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README and metadata if applicable.

See [CONTRIBUTING.md](https://github.com/zuazo/opendkim-cookbook/blob/master/CONTRIBUTING.md).

2018-03-07 07:17 UTC, mburns commented
failed test appears unrelated to code changed:
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/yakkety-backports/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.88.149 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
STDERR: The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

2018-03-07 09:10 UTC, zuazo requested changes
Thanks for your contribution! :smiley:

I'm not sure why you removed the ruby pessimistic operator. If you could, please, clarify the reason for that.

2018-03-07 09:10 UTC, zuazo commented on metadata.rb
> +depends 'yum-epel', '> 0.5'
Even if we update the version number, I think we should conserve the pessimistic operator, shouldn't we?

2018-03-07 10:40 UTC, mburns commented
Hi @zuazo!

I've tweaked the logic to have an upper limit to the valid versions (up to and including the current `~> 3.1`), so that we won't pull in a 4.x version in case they radically change behavior. Good suggestion.

Because of the simple use of `yum-epel`, all versions released (assuming your platform and cookbook dependency graph allows) appear to work for this cookbook's purposes.

Why? For complex run_lists or nodes moving to Chef 13+, it is nice to not be pinned to a dependency version from ~3.5 years ago.

2019-02-19 11:37 UTC, nicutor commented
Hi, I would like to use this cookbook but I can't because of this little thing that was not fixed from about 1 year now.. There was removed only a char to allow upper versions to be got, its that hard to make that change and release a new version?

2019-09-18 23:13 UTC, mburns commented
@zuazo let's merge or close this PR, please. Cheers!

2019-10-09 16:57 UTC, closed without merging